let btn = document.getElementById("start");
console.log(btn);

let budgetValue = document.querySelector('.budget-value');
console.log(budgetValue);
let dayBudgetValue = document.querySelector('.daybudget-value');
console.log(dayBudgetValue);
let levelValue = document.querySelector('.level-value');
console.log(levelValue);
let expensesValue = document.querySelector('.expenses-value');
console.log(expensesValue);
let optionalExpensesValue = document.querySelector('.optionalexpenses-value');
console.log(optionalExpensesValue);
let incomeValue = document.querySelector('.income-value');
console.log(incomeValue);
let monthSavingsValue = document.querySelector('.monthsavings-value');
console.log(monthSavingsValue);
let yearSavingsValue = document.querySelector('.yearsavings-value');
console.log(yearSavingsValue);
let expensesItem = document.querySelectorAll('.expenses-item');
console.log(expensesItem);
let optionalExpensesItem = document.querySelectorAll('.optionalexpenses-item');
console.log(optionalExpensesItem);
let allBtn = document.getElementsByTagName('button');
let expensesItemBtn = allBtn[0];
let optionalExpensesbBtn = allBtn[1];
let countBudgetBtn = allBtn[2];

let chooseIncome = document.querySelector('.choose-income');
console.log(chooseIncome);
let savings = document.querySelector('#savings');
console.log(savings);
let chooseSum = document.querySelector('.choose-sum');
console.log(chooseSum);
let choosePercent = document.querySelector('.choose-percent');
console.log(choosePercent);
let yearValue = document.querySelector('.year-value');
console.log(yearValue);
let monthValue = document.querySelector('.month-value');
console.log(monthValue);
let dayValue = document.querySelector('.day-value');
console.log(dayValue);
